### PR TITLE
CB-7949 add cordova-local to tools release process

### PR DESCRIPTION
**Pull request by stacic**
Additions to the tools release process for the proposed cordova-local utility currently at https://github.com/stacic/cordova-utility

### CODE REVIEW

**Comment by janpio** [comment]
Is anyone using `cordova-local` or can this PR be closed as stale?

**Comment by brodybits** [comment]
What a shame that nobody reviewed this wonderful contribution from 3 years ago, would like to revive it when I get some spare cycles. I just made a fork at <https://github.com/brodybits/cordova-utility> to be sure to preserve it.

FYI I noticed that @stacic (Staci Cooper) is in <http://people.apache.org/committer-index.html> so we know that the needed CLA is in place.

**Comment by raphinesse** [comment]
Why not use `npx cordova`?

**Comment by brodybits** [comment]
> Why not use `npx cordova`?

- extra typing
- not everyone has `npx` (Node 6)

I think the ideal solution would be to have an extremely lightweight CLI that uses scripts from local packages. Not sure how much the newer Node.js tooling works like this or not.

Gotta say that I am starting to agree with your point. I do sometimes use `npx` to run local tooling that is not yet integrated with scripts in package.json. Closing in favor of your point.

**Pull request closed without merging**
