### PR TITLE
Improve plugin release process documentation

### PR DESCRIPTION
**Pull request by janpio**
- More structure
- Move some things around
- Remove JIRA
- Add Release Label
- Fix all the commands

### CODE REVIEW

**Comment by timbru31** [comment]
Another ToDo from https://github.com/apache/cordova-plugin-statusbar/pull/132#issuecomment-465291885 - add a note about the typings version.

**Comment by janpio** [comment]
Let's move this over to apache/cordova and start a discussion about the typings in general.

**Comment by timbru31** [comment]
We already have a typings issue (with the discussion label, too): https://github.com/apache/cordova/issues/39

**Comment by janpio** [comment]
Great. Now we have a second discussion issue about versioning and documentation at https://github.com/apache/cordova/issues/103 ;)

**Pull request merged**
