### PR TITLE
CB-8214 COHO. Rename windowsphone to wp8 to be consistent

### PR DESCRIPTION
**Pull request by sgrebnov**
https://issues.apache.org/jira/browse/CB-8214

### CODE REVIEW

**Comment by nikhilkh** [comment]
@sgrebnov Is this still relevant?

**Comment by nikhilkh** [comment]
@sgrebnov Shall we close this?

**Comment by sgrebnov** [comment]
Re-based and re-tested. I  see that there was similar fix added here: https://github.com/apache/cordova-coho/commit/5a07ec0c711e16695e2ce5a824ae5fee9cf5897f 
But it is still actual since it removes unnecessary logic as well.

**Comment by vladimir-kotikov** [comment]
Looks good :smile:

**Pull request closed without merging**
