### PR TITLE
Cleanup and Improvements

### PR DESCRIPTION
**Pull request by erisu**
### Platforms affected
none

### What does this PR do?
- Remove unsupported/deprecated repos.
- Add Electron Platform Repo
- Added update CDVAvailability support for OSX
- Added Git SSH as an option when cloning.

### What testing has been done on this change?
- npm t
- [Travis CI](https://travis-ci.org/erisu/cordova-coho/builds/482704977)

### CODE REVIEW

**Comment by janpio** [comment]
The old repos had no use? (They were marked as `inactive:true`)

**Comment by erisu** [comment]
IMO, these repos do not have any use once they been identified as deprecated or archived.

Take into account that each repo's README has not been updated with the deprecation notice and also was not archived, but we had said it was deprecated and can be seen in https://github.com/apache/cordova.

Any docs were removed, tracking their status for Apache Status Reports were dropped, and even code was stripped out.

IT is expected that we would never release these repos again. It's better to clean up once it has no use and especially if it been stripped everywhere else.

IMO again, if this inactive flag's sole purpose is to describe that the repo is deprecated, and at the point of no longer receiving new releases, the code should be stripped and the flag doesn't even need to exist.

What other points could the flag give? 
Hope that one day we would support that repo again?
What is that percentage of that happening?

If the idea is that we can enable this flag and go back, well, we already removed deprecated platform specific code from other repos like `cordova-common`. That means it would need to be reimplemented.

Where do we draw a line?

**Comment by janpio** [comment]
Ahem, was it intentional that this response comes across as pretty aggressive? 😮 

I just asked if those repos didn't server any purpose in the codebase - which I would have expected to be answered with a simple "Yes" or "No".

**Comment by brodybits** [comment]
> The old repos had no use? (They were marked as `inactive:true`)

Yes, IMHO

**Comment by brodybits** [comment]
> IMO again, if this inactive flag's sole purpose is to describe that the repo is deprecated, and at the point of no longer receiving new releases, the code should be stripped and the flag doesn't even need to exist.

Agreed on my part as well.

@janpio you did raise an important question, and I think @erisu response was perfectly valid.

**Comment by erisu** [comment]
@janpio Sorry I went overboard on the response to your question and I was wrong for it.
Yes, these repos are no longer used or maintained and can be safely removed.

**Comment by erisu** [comment]
Submitted Separate PRs

**Pull request closed without merging**
