### PR TITLE
Add *draft* tools dependency graph by @raphinesse

### PR DESCRIPTION
**Pull request by brodybits**
### Platforms affected

All

### What does this PR do?

Add _draft_ tools dependency graph from <https://github.com/apache/cordova-discuss/issues/101#issuecomment-402857794> by @raphinesse:

cordova-tooling

_Thanks for guidance: <https://stackoverflow.com/questions/10189356/how-to-add-screenshot-to-readmes-in-github-repository#10189374>_

_To be merged by squash if there are no objections within the next 1-2 days_

### What testing has been done on this change?

Visual inspection

### Checklist

- ~~[Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database~~
- ~~Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.~~
- ~~Added automated test coverage as appropriate for this change.~~

### CODE REVIEW

**Comment by raphinesse** [comment]
Thanks for finding a place to put this. registry-mapper has been removed since I created this. I'll try to find some time to update it.

**Comment by brodybits** [comment]
> registry-mapper has been removed since I created this

in master branch only - added a quick note with this info

> I'll try to find some time to update it.

Considering that this is not yet the case in existing release I would not rush it. Of course the quick solution would be to use "eraser" tool.

Some minor feedback in case you decide to work on the graph again: it is not so clear to me from first glance what order I should publish things in to ensure they are all published with updated dependencies. Reading through the graph I think updates should be published in the following rough order (may not be exact):
- `cordova-common`, `app-hello-world`, `cordova-js`, and `serve`
- `cordova-fetch`
- `cordova-create`
- `cordova-lib`
- Cordova CLI & `plugman`

I think a top-down/bottom-up graph would be more clear. A couple examples from <https://www.ndepend.com/docs/visual-studio-dependency-graph>:

**Comment by raphinesse** [comment]
An online dependency graph editor with capabilities for generating a reverse topological order for the graph would be nice indeed. Unfortunately, I could not find such a tool yet.

**Comment by brodybits** [comment]
Merging (better than nothing, to say the least)

**Comment by raphinesse** [comment]
So I finally found an editor that almost did what I wanted and could be easily modified. [Here it is](https://graphviz2.glitch.me/?graph=digraph+cordovaToolingDependencies+%7B%0A++++node+%5Bfontname+%3D+%22monospace%22%5D%3B%0A%09%0A%09%7Bcordova+lib+fetch+create%7D+-%3E+common%0A%09%7Bplugman+cordova%7D+-%3E+lib%0A%09lib+-%3E+%7Bserve+create+fetch%7D%0A%09create+-%3E+fetch%0A%09%0A%09%23+Not+actually+tooling+but+still+cordova+dependencies%0A%09lib+-%3E+js++%5Bcolor+%3D+grey%5D%0A%09create+-%3E+%22app-hello-world%22+%5Bcolor+%3D+grey%5D%0A%09%22app-hello-world%22++%5Bcolor+%3D+grey%2C+fontcolor+%3D+grey%5D%0A%09js+%5Bcolor+%3D+grey%2C+fontcolor+%3D+grey%5D%0A%7D).

Gives you an edit  and an embed URL.
Cordova Tooling dependency graph

**Pull request merged**
